### ISSUE TITLE
there is no training sets, can you give some samples

### ISSUE THREAD

**Issue by XinhongWu** [lusy/multilabel_classification#1]
As a new fisher in Machine Learning, it is a little difficult for me to reading the src code "svm_test.py".
From the code, I find that the training sets is expressed in the "csv" format.
Can you give me some samples for the training sets ？

**Comment by lusy** [comment]
Hey XinhongWu, I'll have to disappoint you, I'm afraid. It's something we did for a university project a while ago and as far as I remember it was based on a semi-public dataset which we were not authorised to share freely :( (I can't even find it on my pc, which makes me think that we did all the computations on the university machines. Sorry :(
